#!/bin/bash

set -e

echo ***************************************************************************
echo *
echo *  Checking for new kernel packages ...
echo *
echo ***************************************************************************
krnl-install-new

echo
echo ***************************************************************************
echo *
echo *  Removing old kernel packages ...
echo *
echo ***************************************************************************
krnl-clean-old

echo
echo ***************************************************************************
echo *
echo *  Building initrds for new kernels ...
echo *
echo ***************************************************************************
krnl-build-initrds

echo
echo ***************************************************************************
echo *
echo *  Copying kernels and initrds to EFI partition for boot ...
echo *
echo ***************************************************************************
krnl-copy-to-efi

exit 0
